-- Seed generated from data/products.ts. Demo data only.
insert into categories(slug,name,description) values
('casual-wear','Casual Wear','Everyday pieces cut for ease.'),
('formal-wear','Formal Wear','Tailoring with a modern line.'),
('street-style','Street Style','Relaxed shapes, considered details.'),
('outerwear','Outerwear','Coats and jackets for every season.'),
('accessories','Accessories','Leather goods and finishing touches.') on conflict do nothing;
insert into products(slug,sku,name,description,price_cents,sale_price_cents,category_id,tags,badge,materials,care,published) select 'beige-bomber-jacket','BEIGE-BOMBER-JACKET','Beige Bomber Jacket','A lightweight bomber in brushed cotton twill.',18900,null,id,'{jacket,bomber}','BESTSELLER','Responsibly sourced natural fibres.','Dry clean or cold wash; dry flat.',true from categories where slug='outerwear' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Sand','#D8C8B0','BEIGE-BOMBER-JACKET-'||s||'-'||upper(left('Sand',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='beige-bomber-jacket' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Charcoal','#262421','BEIGE-BOMBER-JACKET-'||s||'-'||upper(left('Charcoal',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='beige-bomber-jacket' on conflict do nothing;
insert into products(slug,sku,name,description,price_cents,sale_price_cents,category_id,tags,badge,materials,care,published) select 'smart-casual-blazer','SMART-CASUAL-BLAZER','Smart Casual Blazer','Unstructured blazer with a soft shoulder.',24900,19900,id,'{blazer,tailoring}','SALE','Responsibly sourced natural fibres.','Dry clean or cold wash; dry flat.',true from categories where slug='formal-wear' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Taupe','#9C8B79','SMART-CASUAL-BLAZER-'||s||'-'||upper(left('Taupe',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='smart-casual-blazer' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Black','#000000','SMART-CASUAL-BLAZER-'||s||'-'||upper(left('Black',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='smart-casual-blazer' on conflict do nothing;
insert into products(slug,sku,name,description,price_cents,sale_price_cents,category_id,tags,badge,materials,care,published) select 'knitted-polo-shirt','KNITTED-POLO-SHIRT','Knitted Polo Shirt','Fine-gauge knit polo with a relaxed collar.',8900,null,id,'{polo,knit}','NEW','Responsibly sourced natural fibres.','Dry clean or cold wash; dry flat.',true from categories where slug='casual-wear' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Cream','#F3EEE6','KNITTED-POLO-SHIRT-'||s||'-'||upper(left('Cream',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='knitted-polo-shirt' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Umber','#5E4B3C','KNITTED-POLO-SHIRT-'||s||'-'||upper(left('Umber',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='knitted-polo-shirt' on conflict do nothing;
insert into products(slug,sku,name,description,price_cents,sale_price_cents,category_id,tags,badge,materials,care,published) select 'relaxed-overshirt','RELAXED-OVERSHIRT','Relaxed Overshirt','Heavy cotton overshirt, worn open or buttoned.',12900,null,id,'{overshirt,shirt}',null,'Responsibly sourced natural fibres.','Dry clean or cold wash; dry flat.',true from categories where slug='street-style' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Olive Brown','#6B5A45','RELAXED-OVERSHIRT-'||s||'-'||upper(left('Olive Brown',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='relaxed-overshirt' on conflict do nothing;
insert into products(slug,sku,name,description,price_cents,sale_price_cents,category_id,tags,badge,materials,care,published) select 'textured-wool-coat','TEXTURED-WOOL-COAT','Textured Wool Coat','A long-line coat in a textured wool blend.',39900,31900,id,'{coat,wool}','SALE','Responsibly sourced natural fibres.','Dry clean or cold wash; dry flat.',true from categories where slug='outerwear' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Charcoal','#262421','TEXTURED-WOOL-COAT-'||s||'-'||upper(left('Charcoal',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='textured-wool-coat' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Camel','#B89B72','TEXTURED-WOOL-COAT-'||s||'-'||upper(left('Camel',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='textured-wool-coat' on conflict do nothing;
insert into products(slug,sku,name,description,price_cents,sale_price_cents,category_id,tags,badge,materials,care,published) select 'premium-crewneck','PREMIUM-CREWNECK','Premium Crewneck','Heavyweight loopback cotton sweatshirt.',9900,null,id,'{sweatshirt,crewneck}','NEW','Responsibly sourced natural fibres.','Dry clean or cold wash; dry flat.',true from categories where slug='casual-wear' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Sand','#D8C8B0','PREMIUM-CREWNECK-'||s||'-'||upper(left('Sand',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='premium-crewneck' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Black','#000000','PREMIUM-CREWNECK-'||s||'-'||upper(left('Black',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='premium-crewneck' on conflict do nothing;
insert into products(slug,sku,name,description,price_cents,sale_price_cents,category_id,tags,badge,materials,care,published) select 'tailored-trousers','TAILORED-TROUSERS','Tailored Trousers','Pleated trousers with a tapered leg.',13900,null,id,'{trousers,tailoring}',null,'Responsibly sourced natural fibres.','Dry clean or cold wash; dry flat.',true from categories where slug='formal-wear' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Stone','#CFC4B3','TAILORED-TROUSERS-'||s||'-'||upper(left('Stone',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='tailored-trousers' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Charcoal','#262421','TAILORED-TROUSERS-'||s||'-'||upper(left('Charcoal',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='tailored-trousers' on conflict do nothing;
insert into products(slug,sku,name,description,price_cents,sale_price_cents,category_id,tags,badge,materials,care,published) select 'leather-belt','LEATHER-BELT','Leather Belt','Full-grain leather belt with a brushed buckle.',7900,null,id,'{belt,leather}','BESTSELLER','Responsibly sourced natural fibres.','Dry clean or cold wash; dry flat.',true from categories where slug='accessories' on conflict do nothing;
insert into product_variants(product_id,size,color_name,color_hex,sku,stock) select p.id,s,'Brown','#5E4B3C','LEATHER-BELT-'||s||'-'||upper(left('Brown',3)),20 from products p, unnest(array['S','M','L','XL']) s where p.slug='leather-belt' on conflict do nothing;
